/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oodj.assignment;

import java.awt.Dimension;
import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author tsuta
 */
public class AccountStatus extends javax.swing.JDialog{
    Address add = new Address();
    CreditCard cc = new CreditCard();
    Netbank nb = new Netbank();
    Buyer by = new Buyer();
    Seller se = new Seller();
    Admin adm = new Admin();
    String usname;
    
    public AccountStatus(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public AccountStatus(java.awt.Frame parent, boolean modal, Buyer buy, String us) {
        super(parent, modal);
        initComponents();
        usname = us;
        by = buy;
        add.initialadd(buy);
        cc.initialcc(buy);
        nb.initialnb(buy);
        Address1_Text.setText(add.getline1());
        State_Text.setText(add.getstate());
        Address2_Text.setText(add.getline2());
        CardType_Text.setText(cc.getcardtype());
        Cardnumber_Text.setText(cc.getcardnumber());
        Expirydate_Text.setText(cc.getexpirydate());
        CardPublisher_Text.setText(cc.getcardpublisher());
        Accountnumber_Text.setText(nb.getaccountnumber());
        BankName_Text.setText(nb.getbankname());
        Amountmoney.setText(by.getAmount() + "RM");
    }
    
    public AccountStatus(java.awt.Frame parent, boolean modal, Seller sel, String us) {
        super(parent, modal);
        initComponents();
        usname = us;
        se = sel;
        add.initialadd(se);
        cc.initialcc(sel);
        nb.initialnb(sel);
        this.Amountmoney.setVisible(false);
        this.Charge1.setVisible(false);
        this.Charge2.setVisible(false);
        this.Charge.setVisible(false); 
        Address1_Text.setText(add.getline1());
        State_Text.setText(add.getstate());
        Address2_Text.setText(add.getline2());
        CardType_Text.setText(cc.getcardtype());
        Cardnumber_Text.setText(cc.getcardnumber());
        Expirydate_Text.setText(cc.getexpirydate());
        CardPublisher_Text.setText(cc.getcardpublisher());
        Accountnumber_Text.setText(nb.getaccountnumber());
        BankName_Text.setText(nb.getbankname());
        Amountmoney.setText(sel.getAmount() + "RM");
    }
    
    public AccountStatus(java.awt.Frame parent, boolean modal, Admin ad, String us) {
        super(parent, modal);
        initComponents();
        usname = us;
        adm = ad;
        add.initialadd(adm);
        cc.initialcc(adm);
        nb.initialnb(adm);
        this.Amount.setVisible(false);
        this.Amountmoney.setVisible(false);
        this.Charge.setVisible(false);
        this.Charge1.setVisible(false);
        this.Charge2.setVisible(false);
        Address1_Text.setText(add.getline1());
        State_Text.setText(add.getstate());
        Address2_Text.setText(add.getline2());
        CardType_Text.setText(cc.getcardtype());
        Cardnumber_Text.setText(cc.getcardnumber());
        Expirydate_Text.setText(cc.getexpirydate());
        CardPublisher_Text.setText(cc.getcardpublisher());
        Accountnumber_Text.setText(nb.getaccountnumber());
        BankName_Text.setText(nb.getbankname());
        Amountmoney.setText(adm.getAmount() + "RM");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Background = new javax.swing.JPanel();
        PostalAddress = new javax.swing.JPanel();
        Address1 = new javax.swing.JLabel();
        Address2 = new javax.swing.JLabel();
        State = new javax.swing.JLabel();
        Address1_Text = new javax.swing.JTextField();
        State_Text = new javax.swing.JTextField();
        Address2_Text = new javax.swing.JTextField();
        Method = new javax.swing.JPanel();
        Creditcard = new javax.swing.JPanel();
        Type2 = new javax.swing.JLabel();
        CardNumber = new javax.swing.JLabel();
        CardPublisher = new javax.swing.JLabel();
        ExpiryDate = new javax.swing.JLabel();
        CardType_Text = new javax.swing.JTextField();
        Cardnumber_Text = new javax.swing.JTextField();
        Expirydate_Text = new javax.swing.JTextField();
        CardPublisher_Text = new javax.swing.JTextField();
        Charge1 = new javax.swing.JRadioButton();
        Netbank = new javax.swing.JPanel();
        Type = new javax.swing.JLabel();
        Update = new javax.swing.JButton();
        BankName = new javax.swing.JLabel();
        Accountnumber = new javax.swing.JLabel();
        BankName_Text = new javax.swing.JTextField();
        Accountnumber_Text = new javax.swing.JTextField();
        Amount = new javax.swing.JLabel();
        Amountmoney = new javax.swing.JLabel();
        Charge = new javax.swing.JButton();
        Charge2 = new javax.swing.JRadioButton();

        buttonGroup1.add(Charge1);
        buttonGroup1.add(Charge2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Background.setLayout(new javax.swing.BoxLayout(Background, javax.swing.BoxLayout.Y_AXIS));

        PostalAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Address1.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        Address1.setText("Address-1");

        Address2.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        Address2.setText("Address-2");

        State.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        State.setText("State");

        javax.swing.GroupLayout PostalAddressLayout = new javax.swing.GroupLayout(PostalAddress);
        PostalAddress.setLayout(PostalAddressLayout);
        PostalAddressLayout.setHorizontalGroup(
            PostalAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PostalAddressLayout.createSequentialGroup()
                .addGroup(PostalAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Address1)
                    .addComponent(State)
                    .addComponent(Address2))
                .addGap(56, 56, 56)
                .addGroup(PostalAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Address2_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(State_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Address1_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        PostalAddressLayout.setVerticalGroup(
            PostalAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PostalAddressLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(PostalAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Address1)
                    .addComponent(Address1_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PostalAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Address2)
                    .addComponent(Address2_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PostalAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(State)
                    .addComponent(State_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        Background.add(PostalAddress);

        Method.setLayout(new javax.swing.BoxLayout(Method, javax.swing.BoxLayout.Y_AXIS));

        Creditcard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Type2.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        Type2.setText("Creditcard");

        CardNumber.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        CardNumber.setText("CardNumber:");

        CardPublisher.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        CardPublisher.setText("CardPublisher:");

        ExpiryDate.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        ExpiryDate.setText("Expiry date:");

        Charge1.setText("Charge");

        javax.swing.GroupLayout CreditcardLayout = new javax.swing.GroupLayout(Creditcard);
        Creditcard.setLayout(CreditcardLayout);
        CreditcardLayout.setHorizontalGroup(
            CreditcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreditcardLayout.createSequentialGroup()
                .addGroup(CreditcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreditcardLayout.createSequentialGroup()
                        .addComponent(ExpiryDate)
                        .addGap(31, 31, 31)
                        .addGroup(CreditcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Expirydate_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CardType_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CreditcardLayout.createSequentialGroup()
                        .addGroup(CreditcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CardPublisher)
                            .addComponent(CardNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CreditcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cardnumber_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CardPublisher_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Type2)
                    .addComponent(Charge1))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        CreditcardLayout.setVerticalGroup(
            CreditcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreditcardLayout.createSequentialGroup()
                .addComponent(Type2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CardType_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreditcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CardNumber)
                    .addComponent(Cardnumber_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreditcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CardPublisher)
                    .addComponent(CardPublisher_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreditcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExpiryDate)
                    .addComponent(Expirydate_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Charge1)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        Method.add(Creditcard);

        Netbank.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Type.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        Type.setText("Netbank");

        Update.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        Update.setText("Update");
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateMouseClicked(evt);
            }
        });

        BankName.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        BankName.setText("BankName:");

        Accountnumber.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        Accountnumber.setText("Account Number:");

        Amount.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        Amount.setText("Amount");

        Amountmoney.setFont(new java.awt.Font("NSimSun", 0, 48)); // NOI18N

        Charge.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        Charge.setText("Charge");
        Charge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChargeMouseClicked(evt);
            }
        });

        Charge2.setText("Charge");

        javax.swing.GroupLayout NetbankLayout = new javax.swing.GroupLayout(Netbank);
        Netbank.setLayout(NetbankLayout);
        NetbankLayout.setHorizontalGroup(
            NetbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NetbankLayout.createSequentialGroup()
                .addComponent(Type)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Amount)
                .addGap(168, 168, 168))
            .addGroup(NetbankLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Charge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Update))
            .addGroup(NetbankLayout.createSequentialGroup()
                .addGroup(NetbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NetbankLayout.createSequentialGroup()
                        .addComponent(BankName)
                        .addGap(66, 66, 66)
                        .addComponent(BankName_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Amountmoney, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NetbankLayout.createSequentialGroup()
                        .addComponent(Accountnumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Accountnumber_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Charge2))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        NetbankLayout.setVerticalGroup(
            NetbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NetbankLayout.createSequentialGroup()
                .addGroup(NetbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NetbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Type)
                        .addComponent(Amount))
                    .addGroup(NetbankLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(NetbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BankName)
                            .addComponent(BankName_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Amountmoney))
                        .addGap(2, 2, 2)
                        .addGroup(NetbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Accountnumber)
                            .addComponent(Accountnumber_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(Charge2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(NetbankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Update)
                    .addComponent(Charge)))
        );

        Method.add(Netbank);

        Background.add(Method);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
         * Following UpdateMouseClicked code was referenced from (Paul Deitel, 2012, p566 - p567)
     */
    
    private void UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseClicked
        try{
            File file = new File("Textfiles/Address.txt");
            File file1 = new File("Textfiles/Credit Card.txt");
            File file2 = new File("Textfiles/Netbank.txt");
            boolean exist = false;
            
            BufferedReader br = new BufferedReader(new FileReader(file));
            ArrayList<String> l1 = new ArrayList<String>();
            String str;
            
            while((str = br.readLine()) != null){
               if(str.equals(usname)){
                    l1.add(usname);
                    l1.add(Address1_Text.getText());
                    l1.add(State_Text.getText());
                    l1.add(Address2_Text.getText());
                    str= br.readLine();
                    str= br.readLine();
                    str= br.readLine();
                    exist =true;
                }
                
                else{
                    l1.add(str);
                }
            }
            
            br.close();
            BufferedWriter wr = new BufferedWriter(new FileWriter(file));
            if(exist){
                for(int i =0 ; i < l1.size() ; i++ ){
                wr.write(l1.get(i));
                wr.write("\r\n");
                }
            }
            else{
                for(int i =0 ; i < l1.size() ; i++ ){
                wr.write(l1.get(i));
                wr.write("\r\n");
                }
                wr.write(usname + "\r\n");
                wr.write(Address1_Text.getText() + "\r\n");
                wr.write(State_Text.getText() + "\r\n");
                wr.write(Address2_Text.getText() + "\r\n");
                wr.write("," + "\r\n");
            }
            
            wr.close();
            
            exist = false;
            BufferedReader br1 = new BufferedReader(new FileReader(file1));
            ArrayList<String> l2 = new ArrayList<String>();
            
            while((str = br1.readLine()) != null){
               if(str.equals(usname)){
                    l2.add(usname);
                    l2.add(CardType_Text.getText());
                    l2.add(Cardnumber_Text.getText());
                    l2.add(Expirydate_Text.getText());
                    l2.add(CardPublisher_Text.getText());
                    str= br1.readLine();
                    str= br1.readLine();
                    str= br1.readLine();
                    str= br1.readLine();
                }
                
                else{
                    l2.add(str);
                }
            }
            
            br1.close();
            BufferedWriter wr1 = new BufferedWriter(new FileWriter(file1));
            if(exist){
                for(int j = 0 ; j < l2.size() ; j++ ){
                wr1.write(l2.get(j));
                wr1.write("\r\n");
                }
            }
            else{
                for(int j = 0 ; j < l2.size() ; j++ ){
                wr1.write(l2.get(j));
                wr1.write("\r\n");
                }
                wr1.write(usname + "\r\n");
                wr1.write(CardType_Text.getText() + "\r\n");
                wr1.write(Cardnumber_Text.getText() + "\r\n");
                wr1.write(Expirydate_Text.getText() + "\r\n");
                wr1.write(CardPublisher_Text.getText() + "\r\n");
                wr1.write("," + "\r\n");
            }            
            wr1.close();
            
            BufferedReader br2 = new BufferedReader(new FileReader(file2));
            ArrayList<String> l3 = new ArrayList<String>();
            exist = false;
            
            while((str = br2.readLine()) != null){
               if(str.equals(usname)){
                    l3.add(usname);
                    l3.add(BankName_Text.getText());
                    l3.add(Accountnumber_Text.getText());
                    str= br2.readLine();
                    str= br2.readLine();
                    exist = true;
                }
                
                else{
                    l3.add(str);
                }
            }
            
            br2.close();
            BufferedWriter wr2 = new BufferedWriter(new FileWriter(file2));
            if(exist){
                for(int i =0 ; i < l3.size() ; i++ ){
                wr2.write(l3.get(i));
                wr2.write("\r\n");
                }
            }
            else{
                for(int i =0 ; i < l3.size() ; i++ ){
                wr2.write(l3.get(i));
                wr2.write("\r\n");
                }
                wr2.write(usname + "\r\n");
                wr2.write(BankName_Text.getText() + "\r\n");
                wr2.write(Accountnumber_Text.getText() + "\r\n");
                wr2.write("," + "\r\n");
            }
            
            wr2.close();
            JOptionPane.showMessageDialog(null, "Succeeded to update your info.");
        }
        
       catch(FileNotFoundException e){
            System.out.println(e);
        }
       
        catch(IOException e){
            System.out.println(e);
        }
        
        
    }//GEN-LAST:event_UpdateMouseClicked

    private void ChargeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChargeMouseClicked
        boolean credit = Charge1.isSelected();
        boolean netbank = Charge2.isSelected();
        
        try{
            File file = new File("Textfiles/Customer.txt");
            String option = JOptionPane.showInputDialog(null, "How much you want to charge in your account?");
        
            if(!(by.getUsername().isEmpty())){
            ArrayList<String> str = by.take_out(file);
            
            for(int i = 0; i < str.size() ; i++){
                if(str.get(i).equals(by.getUsername())){
                    str.set(i + 2, Integer.toString(Integer.parseInt(str.get(i + 2)) + Integer.parseInt(option)));
                    str.set(i + 3, ",");
                    break;
                }
            }
            
            BufferedWriter wr = new BufferedWriter(new FileWriter(file));
            
            for(String d : str){
                wr.write(d + "\r\n");
            }
            wr.close();
            
            }
        
            else if(!(se.getUsername().isEmpty())){
            ArrayList<String> str = se.take_out(file);
            
            for(int i = 0; i < str.size() ; i++){
                if(str.get(i).equals(se.getUsername())){
                    str.set(i + 2, Integer.toString(Integer.parseInt(str.get(i + 2)) + Integer.parseInt(option)));
                    str.add(i + 3, "");
                    break;
                }
            }
            
            BufferedWriter wr = new BufferedWriter(new FileWriter(file));
            for(String d : str){
                wr.write(d + "\r\n");
            }
            wr.close();
            }
        }
        
        catch(FileNotFoundException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        
        catch(IOException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_ChargeMouseClicked

    
    public void initial(int x, int y){
        //Set Title//
        this.setTitle("AccountStatus");
        Dimension dim = new Dimension(x,y);
        //Set size//
        this.setPreferredSize(dim);
        this.setMaximumSize(dim);
        this.setMinimumSize(dim);
        //Set location on the central of screen//
        this.setLocationRelativeTo(null);
        //the page can't be changeable//
        this.setResizable(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AccountStatus dialog = new AccountStatus(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Accountnumber;
    private javax.swing.JTextField Accountnumber_Text;
    private javax.swing.JLabel Address1;
    private javax.swing.JTextField Address1_Text;
    private javax.swing.JLabel Address2;
    private javax.swing.JTextField Address2_Text;
    private javax.swing.JLabel Amount;
    private javax.swing.JLabel Amountmoney;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel BankName;
    private javax.swing.JTextField BankName_Text;
    private javax.swing.JLabel CardNumber;
    private javax.swing.JLabel CardPublisher;
    private javax.swing.JTextField CardPublisher_Text;
    private javax.swing.JTextField CardType_Text;
    private javax.swing.JTextField Cardnumber_Text;
    private javax.swing.JButton Charge;
    private javax.swing.JRadioButton Charge1;
    private javax.swing.JRadioButton Charge2;
    private javax.swing.JPanel Creditcard;
    private javax.swing.JLabel ExpiryDate;
    private javax.swing.JTextField Expirydate_Text;
    private javax.swing.JPanel Method;
    private javax.swing.JPanel Netbank;
    private javax.swing.JPanel PostalAddress;
    private javax.swing.JLabel State;
    private javax.swing.JTextField State_Text;
    private javax.swing.JLabel Type;
    private javax.swing.JLabel Type2;
    private javax.swing.JButton Update;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
