/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oodj.assignment;
import java.io.*;
import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

/**
 *
 * @author tsuta
 */
public class Products extends javax.swing.JFrame{

    /**
     * Creates new form Products
     */
    //These are classes for providing different services//
    Buyer buy = new Buyer();
    Seller sel = new Seller();
    Admin adm = new Admin();
    
    public Products() {
        initComponents();
    }

    public Products(Buyer by) {
        buy = by;
        initComponents();
        this.Usernamereciever.setText("UserName:"+buy.getUsername()); 
        this.Accounttypereciever.setText("Account:Buyer");
        Change.setVisible(false);
        New_add.setVisible(false);
        File file = new File("Textfiles/Products on sale.txt");
        ArrayList<JScrollPane> scroll = new ArrayList<JScrollPane>();
        for(int i = 0 ; i < Itemlist.getComponentCount() ; i++){
            scroll.add((JScrollPane)Itemlist.getComponent(i));
        }
        
        for(JScrollPane s:scroll){
            buy.ShowingItem(file, s.getName(), s.getViewport());
        }
    }

    public Products(Seller se) {
        sel = se;
        initComponents();
        this.Usernamereciever.setText("UserName:"+sel.getUsername());   
        this.Accounttypereciever.setText("Account:Seller");
        this.New_add.setVisible(false);
        File file = new File("Textfiles/Products on sale.txt");
        ArrayList<JScrollPane> scroll = new ArrayList<JScrollPane>();
        
        for(int i = 0 ; i < Itemlist.getComponentCount() ; i++){
            scroll.add((JScrollPane)Itemlist.getComponent(i));
        }
        
        for(JScrollPane s:scroll){
            sel.ShowingItem(file, s.getName(), s.getViewport(), this.Sales.getText());
        }
    }

    public Products(Admin ad) {
        adm = ad;
        initComponents();
        this.Usernamereciever.setText("UserName:"+adm.getUsername());   
        this.Accounttypereciever.setText("Account:Admin");
        File file = new File("Textfiles/Products on sale.txt");
        ArrayList<JScrollPane> scroll = new ArrayList<JScrollPane>();
        
        for(int i = 0 ; i < Itemlist.getComponentCount() ; i++){
            scroll.add((JScrollPane)Itemlist.getComponent(i));
        }
        
        for(JScrollPane s:scroll){
            adm.ShowingItem(file, s.getName(), s.getViewport(), this.Sales.getText());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Productlist = new javax.swing.JPanel();
        Itemlist = new javax.swing.JTabbedPane();
        All = new javax.swing.JScrollPane();
        Hat = new javax.swing.JScrollPane();
        Shoes = new javax.swing.JScrollPane();
        Coat = new javax.swing.JScrollPane();
        Gloves = new javax.swing.JScrollPane();
        Clothes = new javax.swing.JScrollPane();
        Header = new javax.swing.JPanel();
        Back = new javax.swing.JPanel();
        Log_out = new javax.swing.JButton();
        Change = new javax.swing.JButton();
        Sales = new javax.swing.JLabel();
        Reload = new javax.swing.JButton();
        New_add = new javax.swing.JButton();
        Log = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Account = new javax.swing.JPanel();
        Usernamereciever = new javax.swing.JLabel();
        Accounttypereciever = new javax.swing.JLabel();
        Flavor = new javax.swing.JLabel();
        Go_account = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Productlist.setPreferredSize(new java.awt.Dimension(1050, 300));

        Itemlist.setPreferredSize(new java.awt.Dimension(1050, 300));
        Itemlist.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ItemlistComponentShown(evt);
            }
        });

        All.setName("All"); // NOI18N
        All.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                AllComponentShown(evt);
            }
        });
        Itemlist.addTab("All", All);

        Hat.setName("Hat"); // NOI18N
        Hat.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                HatComponentShown(evt);
            }
        });
        Itemlist.addTab("Hat", Hat);

        Shoes.setName("Shoes"); // NOI18N
        Shoes.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ShoesComponentShown(evt);
            }
        });
        Itemlist.addTab("Shoes", Shoes);

        Coat.setName("Coat"); // NOI18N
        Coat.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                CoatComponentShown(evt);
            }
        });
        Itemlist.addTab("Coat", Coat);

        Gloves.setName("Gloves"); // NOI18N
        Gloves.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                GlovesComponentShown(evt);
            }
        });
        Itemlist.addTab("Gloves", Gloves);

        Clothes.setName("Clothes"); // NOI18N
        Clothes.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ClothesComponentShown(evt);
            }
        });
        Itemlist.addTab("Clothes", Clothes);

        javax.swing.GroupLayout ProductlistLayout = new javax.swing.GroupLayout(Productlist);
        Productlist.setLayout(ProductlistLayout);
        ProductlistLayout.setHorizontalGroup(
            ProductlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Itemlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ProductlistLayout.setVerticalGroup(
            ProductlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Itemlist, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
        );

        Header.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Header.setPreferredSize(new java.awt.Dimension(1050, 200));
        Header.setLayout(new javax.swing.BoxLayout(Header, javax.swing.BoxLayout.Y_AXIS));

        Back.setPreferredSize(new java.awt.Dimension(1050, 30));
        Back.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        Log_out.setText("Logout");
        Log_out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Log_outMouseClicked(evt);
            }
        });
        Log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Log_outActionPerformed(evt);
            }
        });
        Back.add(Log_out);

        Change.setText("Change");
        Change.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangeMouseClicked(evt);
            }
        });
        Back.add(Change);

        Sales.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        Sales.setText("On sale");
        Back.add(Sales);

        Reload.setText("Reload");
        Reload.setAlignmentX(1.0F);
        Reload.setInheritsPopupMenu(true);
        Reload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReloadMouseClicked(evt);
            }
        });
        Back.add(Reload);

        New_add.setText("New Product");
        New_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                New_addMouseClicked(evt);
            }
        });
        Back.add(New_add);

        Header.add(Back);

        Log.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Log.setPreferredSize(new java.awt.Dimension(1050, 100));

        Logo.setFont(new java.awt.Font("NSimSun", 1, 48)); // NOI18N
        Logo.setText("Preloved System");
        Log.add(Logo);

        Header.add(Log);

        Account.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 50, 5));

        Usernamereciever.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        Usernamereciever.setText("UserName:");
        Account.add(Usernamereciever);

        Accounttypereciever.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        Accounttypereciever.setText("Account:");
        Account.add(Accounttypereciever);

        Flavor.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        Flavor.setText("Here is your account page. Go there!");
        Account.add(Flavor);

        Go_account.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        Go_account.setText("Account Page");
        Go_account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Go_accountMouseClicked(evt);
            }
        });
        Account.add(Go_account);

        Header.add(Account);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Productlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(Productlist, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AllComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_AllComponentShown
        
    }//GEN-LAST:event_AllComponentShown

    private void HatComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_HatComponentShown
       
    }//GEN-LAST:event_HatComponentShown
    
    
    private void ShoesComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ShoesComponentShown
      
    }//GEN-LAST:event_ShoesComponentShown

    private void CoatComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_CoatComponentShown
       
    }//GEN-LAST:event_CoatComponentShown

    private void GlovesComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_GlovesComponentShown
        
    }//GEN-LAST:event_GlovesComponentShown

    private void ClothesComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ClothesComponentShown
        
    }//GEN-LAST:event_ClothesComponentShown

    private void ItemlistComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ItemlistComponentShown

    }//GEN-LAST:event_ItemlistComponentShown

    private void Log_outMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Log_outMouseClicked
        Login login = new Login();
        login.initial(500, 500);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Log_outMouseClicked

    private void Log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log_outActionPerformed
        
    }//GEN-LAST:event_Log_outActionPerformed

    private void ReloadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReloadMouseClicked
        reload();
    }//GEN-LAST:event_ReloadMouseClicked

    private void Go_accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Go_accountMouseClicked
        if(!(buy.getFirstname().equals(""))){
            Account newac = new Account(this, buy);
            newac.initial(this.getWidth(), this.getHeight());
            newac.setVisible(true);
            this.dispose();
        }
        
        else if(!(sel.getFirstname().equals(""))){
            Account newac = new Account(this, sel);
            newac.initial(this.getWidth(), this.getHeight());
            newac.setVisible(true);
            this.dispose();
        }
        
        else{
            Account newac = new Account(this, adm);
            newac.initial(this.getWidth(), this.getHeight());
            newac.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_Go_accountMouseClicked

    private void ChangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangeMouseClicked
        if(Sales.getText().equals("On sale"))
        {
            if(!(sel.getFirstname().equals(""))){
                File file = new File("Textfiles/Products off sale.txt");
                ArrayList<JScrollPane> scroll = new ArrayList<JScrollPane>();
                
                for(int i = 0 ; i < Itemlist.getComponentCount() ; i++){
                    scroll.add((JScrollPane)Itemlist.getComponent(i));
                }
        
                for(JScrollPane s:scroll){
                   sel.ShowingItem(file, s.getName(), s.getViewport(), "Off sale");
                }
                Sales.setText("Off sale");
            }
        
            else if(!(adm.getFirstname().equals(""))){
                File file = new File("Textfiles/Products off sale.txt");
                ArrayList<JScrollPane> scroll = new ArrayList<JScrollPane>();
                
                for(int i = 0 ; i < Itemlist.getComponentCount() ; i++){
                    scroll.add((JScrollPane)Itemlist.getComponent(i));
                }
        
                for(JScrollPane s:scroll){
                    adm.ShowingItem(file, s.getName(), s.getViewport(), "Off sale");
                }
                Sales.setText("Off sale");
            }
            
        }
        
        else{
            if(!(sel.getFirstname().equals(""))){
            File file = new File("Textfiles/Products on sale.txt");
                ArrayList<JScrollPane> scroll = new ArrayList<JScrollPane>();
                
                for(int i = 0 ; i < Itemlist.getComponentCount() ; i++){
                    scroll.add((JScrollPane)Itemlist.getComponent(i));
                }
        
                for(JScrollPane s:scroll){
                    sel.ShowingItem(file, s.getName(), s.getViewport(), "On sale");
                }
                Sales.setText("On sale");
            }
        
            else if(!(adm.getFirstname().equals(""))){
                File file = new File("Textfiles/Products on sale.txt");
                ArrayList<JScrollPane> scroll = new ArrayList<JScrollPane>();
                
                for(int i = 0 ; i < Itemlist.getComponentCount() ; i++){
                    scroll.add((JScrollPane)Itemlist.getComponent(i));
                }
        
                for(JScrollPane s:scroll){
                    adm.ShowingItem(file, s.getName(), s.getViewport(), "On sale");
                }
                Sales.setText("On sale");
            }
            
        }
        
        
    }//GEN-LAST:event_ChangeMouseClicked

    private void New_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_addMouseClicked
        Updateproduct up = new Updateproduct(this, true);
        up.initial(500, 350);
        up.setVisible(true);
    }//GEN-LAST:event_New_addMouseClicked
    
 
    public void initial(int x, int y){
        //Set Title//
        this.setTitle("Products:"+ Accounttypereciever.getText());
        Dimension dim = new Dimension(x,y);
        //Set size//
        this.setPreferredSize(dim);
        this.setMaximumSize(dim);
        this.setMinimumSize(dim);
        //Set location on the central of screen//
        this.setLocationRelativeTo(null);
        //the page can't be changeable//
        this.setResizable(false);
    }
    
    //Reloading page//
    public void reload(){
        if(!(buy.getFirstname().equals(""))){
            Products New = new Products(buy);
            New.initial(this.getWidth(), this.getHeight());
            New.setVisible(true);
            this.dispose();
        }
        
        else if(!(sel.getFirstname().equals(""))){
            Products New = new Products(sel);
            New.initial(this.getWidth(), this.getHeight());
            New.setVisible(true);
            this.dispose();
        }
        else{
            Products New = new Products(adm);
            New.initial(this.getWidth(), this.getHeight());
            New.setVisible(true);
            this.dispose();
            }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Products().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Account;
    private javax.swing.JLabel Accounttypereciever;
    private javax.swing.JScrollPane All;
    private javax.swing.JPanel Back;
    private javax.swing.JButton Change;
    private javax.swing.JScrollPane Clothes;
    private javax.swing.JScrollPane Coat;
    private javax.swing.JLabel Flavor;
    private javax.swing.JScrollPane Gloves;
    private javax.swing.JButton Go_account;
    private javax.swing.JScrollPane Hat;
    private javax.swing.JPanel Header;
    private javax.swing.JTabbedPane Itemlist;
    private javax.swing.JPanel Log;
    private javax.swing.JButton Log_out;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton New_add;
    private javax.swing.JPanel Productlist;
    private javax.swing.JButton Reload;
    private javax.swing.JLabel Sales;
    private javax.swing.JScrollPane Shoes;
    private javax.swing.JLabel Usernamereciever;
    // End of variables declaration//GEN-END:variables
}
