/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oodj.assignment;

import java.awt.Dimension;
import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author tsuta
 */
public class UpdateAccount extends javax.swing.JDialog{

    /**
     * Creates new form UpdateAccount
     */
    Buyer by = new Buyer();
    Seller se = new Seller();
    Admin ad = new Admin();
    
    public UpdateAccount(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public UpdateAccount(java.awt.Frame parent, boolean modal, Buyer buy) {
        super(parent, modal);
        initComponents();
        by = buy;
        FirstName_Text.setText(by.getFirstname());
        LastName_Text.setText(by.getLastname());
        Mail_Text.setText(by.getmail());
        Phone_Text.setText(by.getPhone());
        UserName_Text.setText(by.getUsername());
        Password_Text.setText(by.getPassword());
    }
    
    public UpdateAccount(java.awt.Frame parent, boolean modal, Seller sel) {
        super(parent, modal);
        initComponents();
        se = sel;
        FirstName_Text.setText(se.getFirstname());
        LastName_Text.setText(se.getLastname());
        Mail_Text.setText(se.getmail());
        Phone_Text.setText(se.getPhone());
        UserName_Text.setText(se.getUsername());
        Password_Text.setText(se.getPassword());
    }
    
    public UpdateAccount(java.awt.Frame parent, boolean modal, Admin adm) {
        super(parent, modal);
        initComponents();
        ad = adm;
        FirstName_Text.setText(ad.getFirstname());
        LastName_Text.setText(ad.getLastname());
        Mail_Text.setText(ad.getmail());
        Phone_Text.setText(ad.getPhone());
        UserName_Text.setText(ad.getUsername());
        Password_Text.setText(ad.getPassword());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        FirstName = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        Mail = new javax.swing.JLabel();
        Phone = new javax.swing.JLabel();
        UserName = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        FirstName_Text = new javax.swing.JTextField();
        LastName_Text = new javax.swing.JTextField();
        Mail_Text = new javax.swing.JTextField();
        Phone_Text = new javax.swing.JTextField();
        UserName_Text = new javax.swing.JTextField();
        Password_Text = new javax.swing.JTextField();
        Update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        FirstName.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        FirstName.setText("First Name:");

        LastName.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        LastName.setText("Last Name:");

        Mail.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        Mail.setText("E-mail:");

        Phone.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        Phone.setText("Phone:");

        UserName.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        UserName.setText("UserName:");

        Password.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        Password.setText("Password:");

        FirstName_Text.setName("FirstName_Text"); // NOI18N

        LastName_Text.setName("LastName_Text"); // NOI18N

        Mail_Text.setName("Mail_Text"); // NOI18N

        Phone_Text.setName("Phone_Text"); // NOI18N

        UserName_Text.setName("UserName_Text"); // NOI18N

        Password_Text.setName("Password_Text"); // NOI18N

        Update.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(FirstName)
                        .addGroup(BackgroundLayout.createSequentialGroup()
                            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(LastName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Mail, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Phone, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(UserName, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(9, 9, 9)))
                    .addComponent(Password))
                .addGap(36, 36, 36)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(Password_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(Update))
                    .addComponent(FirstName_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserName_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Phone_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mail_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastName_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstName)
                    .addComponent(FirstName_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastName)
                    .addComponent(LastName_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mail)
                    .addComponent(Mail_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Phone)
                    .addComponent(Phone_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserName)
                    .addComponent(UserName_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password)
                    .addComponent(Password_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Update))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        try{
            File file = new File("Textfiles/Customer.txt");
            
            if(!(by.getFirstname().equals(""))){
                ArrayList<String> l1 = by.take_out(file);
                BufferedWriter wr1 = new BufferedWriter(new FileWriter(file));
            
                for(int i = 0 ; i < l1.size() ; i++){
                    if(l1.get(i).equals(by.getPassword())){
                        l1.set(i, Password_Text.getText());
                        l1.set(i + 1, FirstName_Text.getText());
                        l1.set(i + 2, LastName_Text.getText());
                        l1.set(i + 3, Mail_Text.getText());
                        l1.set(i + 4, Phone_Text.getText());
                        l1.set(i + 5, UserName_Text.getText());
                        break;
                    }
                }
                
                for(int i =0 ; i < l1.size() ; i++ ){
                wr1.write(l1.get(i));
                wr1.write("\r\n");
                }
                wr1.close();
                JOptionPane.showMessageDialog(null, "The update has been finished safely");
                this.dispose();
            }
        
            else if(!(se.getFirstname().equals(""))){
                ArrayList<String> l2 = se.take_out(file);
                BufferedWriter wr2 = new BufferedWriter(new FileWriter(file));
            
                for(int i = 0 ; i < l2.size() ; i++){
                    if(l2.get(i).equals(se.getPassword())){
                        l2.set(i, Password_Text.getText());
                        l2.set(i + 1, FirstName_Text.getText());
                        l2.set(i + 2, LastName_Text.getText());
                        l2.set(i + 3, Mail_Text.getText());
                        l2.set(i + 4, Phone_Text.getText());
                        l2.set(i + 5, UserName_Text.getText());
                        break;
                    }
                }
                
                for(int i =0 ; i < l2.size() ; i++ ){
                wr2.write(l2.get(i));
                wr2.write("\r\n");
                }
                wr2.close();
                this.dispose();
            }
        
            else{
                ArrayList<String> l3 = ad.take_out(file);
                BufferedWriter wr3 = new BufferedWriter(new FileWriter(file));
            
                for(int i = 0 ; i < l3.size() ; i++){
                    if(l3.get(i).equals(ad.getPassword())){
                        l3.set(i, Password_Text.getText());
                        l3.set(i + 1, FirstName_Text.getText());
                        l3.set(i + 2, LastName_Text.getText());
                        l3.set(i + 3, Mail_Text.getText());
                        l3.set(i + 4, Phone_Text.getText());
                        l3.set(i + 5, UserName_Text.getText());
                        break;
                    }
                }
                
                for(int i =0 ; i < l3.size() ; i++ ){
                wr3.write(l3.get(i));
                wr3.write("\r\n");
                }
                wr3.close();
                JOptionPane.showMessageDialog(null, "The update has been finished safely");
                this.dispose();
            }
        }
    
        catch(FileNotFoundException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        
        catch(IOException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_UpdateActionPerformed

    public void initial(int x, int y){
        //Set Title//
        this.setTitle("Updateproduct");
        Dimension dim = new Dimension(x,y);
        //Set size//
        this.setPreferredSize(dim);
        this.setMaximumSize(dim);
        this.setMinimumSize(dim);
        //Set location on the central of screen//
        this.setLocationRelativeTo(null);
        //the page can't be changeable//
        this.setResizable(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateAccount dialog = new UpdateAccount(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel FirstName;
    private javax.swing.JTextField FirstName_Text;
    private javax.swing.JLabel LastName;
    private javax.swing.JTextField LastName_Text;
    private javax.swing.JLabel Mail;
    private javax.swing.JTextField Mail_Text;
    private javax.swing.JLabel Password;
    private javax.swing.JTextField Password_Text;
    private javax.swing.JLabel Phone;
    private javax.swing.JTextField Phone_Text;
    private javax.swing.JButton Update;
    private javax.swing.JLabel UserName;
    private javax.swing.JTextField UserName_Text;
    // End of variables declaration//GEN-END:variables
}
