/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oodj.assignment;

import java.awt.*;
import java.io.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.border.BevelBorder;

/**
 *
 * @author tsuta
 */
public class Viewallaccount extends javax.swing.JDialog implements FrameVisualization{

    /**
     * Creates new form Viewallaccount
     */
    public Viewallaccount(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Showingtransaction();
    }
    @Override
    public void initial(int x, int y){
        //Set Title//
        this.setTitle("All Account");
        Dimension dim = new Dimension(x,y);
        //Set size//
        this.setPreferredSize(dim);
        this.setMaximumSize(dim);
        this.setMinimumSize(dim);
        //Set location on the central of screen//
        this.setLocationRelativeTo(null);
        //the page can't be changeable//
        this.setResizable(false);
    }
    
    private void Showingtransaction(){
            File file = new File("Textfiles/Customer.txt");
            JViewport view = this.Accountlist.getViewport();
            ArrayList<String> cus = take_out(file);
            JPanel back = new JPanel();
            back.setBackground(Color.red);
            back.setLayout(new BoxLayout(back, BoxLayout.Y_AXIS));
            
            for(int i = 0 ; i < cus.size() ; i++){
                if(!(cus.get(i).equals(""))){
                    JPanel pro = new JPanel();
                    pro.setPreferredSize(new Dimension(back.getWidth(), 200));
                    BevelBorder bor = new BevelBorder(BevelBorder.RAISED);
                    pro.setBorder(bor);
                    pro.setLayout(new BoxLayout(pro, BoxLayout.Y_AXIS));
               
                    JPanel p1 = new JPanel();
                    p1.setPreferredSize(new Dimension(back.getWidth(), 50));
                    JLabel l1 = new JLabel("UserName:"+ cus.get( i + 5 ));
                    l1.setFont(new Font("NSimSun", Font.PLAIN, 36));
                    p1.add(l1);
                
                    JPanel p2 = new JPanel();
                    p2.setPreferredSize(new Dimension(back.getWidth(), 150));
                    p2.setLayout(new BoxLayout(p2, BoxLayout.Y_AXIS));
                    JLabel l2 = new JLabel("Password:" + cus.get(i));
                    l2.setFont(new Font("NSimSun", Font.PLAIN, 18));
                    JLabel l3 = new JLabel("FirstName:"+ cus.get(i + 1));
                    l3.setFont(new Font("NSimSun", Font.PLAIN, 18));
                    JLabel l4 = new JLabel("LastName:"+ cus.get(i + 2));
                    l4.setFont(new Font("NSimSun", Font.PLAIN, 18));
                    JLabel l5 = new JLabel("E-mail:"+ cus.get(i + 3));
                    l5.setFont(new Font("NSimSun", Font.PLAIN, 18));
                    JLabel l6 = new JLabel("Phone:"+ cus.get(i + 4));
                    l6.setFont(new Font("NSimSun", Font.PLAIN, 18));
                    JLabel l7 = new JLabel("Account Type:"+ cus.get(i + 6));
                    l7.setFont(new Font("NSimSun", Font.PLAIN, 18));
                    p2.add(l2);
                    p2.add(l3);
                    p2.add(l4);
                    p2.add(l5);
                    p2.add(l6);
                    p2.add(l7);
                
                    pro.add(p1);
                    pro.add(p2);
                    back.add(pro);
                    i += 7;
                }
            }
            view.add(back);
    }
    
    
    /**
         * Following take_out code was referenced from (Paul Deitel, 2012, p554 - p555)
     */
    private ArrayList<String> take_out (File file){
        ArrayList<String> _return = new ArrayList<String>();
        
        try{
            String str;
            BufferedReader br = new BufferedReader(new FileReader(file));
            //Reading data until the end//
            while((str = br.readLine()) != null){
                _return.add(str);
            }
        }

        catch(IOException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        return _return;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Delete = new javax.swing.JButton();
        Authentification = new javax.swing.JButton();
        Contents = new javax.swing.JPanel();
        Accountlist = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Header.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Logo.setFont(new java.awt.Font("NSimSun", 0, 36)); // NOI18N
        Logo.setText("All User Account");

        Delete.setText("Delete");
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
        });

        Authentification.setText("Authentification");
        Authentification.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AuthentificationMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(Delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Authentification)
                .addGap(29, 29, 29))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Logo)
                    .addComponent(Delete)
                    .addComponent(Authentification))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ContentsLayout = new javax.swing.GroupLayout(Contents);
        Contents.setLayout(ContentsLayout);
        ContentsLayout.setHorizontalGroup(
            ContentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Accountlist)
        );
        ContentsLayout.setVerticalGroup(
            ContentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Accountlist, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Contents, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
        String option = JOptionPane.showInputDialog(null, "Which accout you want to remove?\nPlease type user name.");
        File file = new File("Textfiles/Customer.txt");
        ArrayList<String> str = take_out(file);
        for(int i = 0; i < str.size(); i++){
            if(str.get(i).equals(option)){
                str.remove(i - 5);
                str.remove(i - 5);
                str.remove(i - 5);
                str.remove(i - 5);
                str.remove(i - 5);
                str.remove(i - 5);
                str.remove(i - 5);
                str.remove(i - 5);
                JOptionPane.showMessageDialog(null, "The account has been removed safely");
                break;
            }
        }
        
        try{
        BufferedWriter wr = new BufferedWriter(new FileWriter(file));
        for(String k :str){
            wr.write(k + "\r\n");
        }
        wr.write("\r\n");
        wr.close();    
        }
        catch(IOException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_DeleteMouseClicked

    /**
         * Following writing code was referenced from (Paul Deitel, 2012, p566 - p567)
     */
    private void AuthentificationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AuthentificationMouseClicked
        String option = JOptionPane.showInputDialog(null, "Which accout you want up to Admin?\nPlease type user name.");
        File file = new File("Textfiles/Customer.txt");
        ArrayList<String> str = take_out(file);
        for(int i = 0; i < str.size(); i++){
            if(str.get(i).equals(option)){
                str.set(i + 1, "Admin");
                JOptionPane.showMessageDialog(null, "The account has been changed safely");
                break;
            }
        }
        try{
        BufferedWriter wr = new BufferedWriter(new FileWriter(file));
        for(String k :str){
            wr.write(k + "\r\n");
        }
        wr.write("\r\n");
        wr.close();    
        }
        catch(IOException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_AuthentificationMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viewallaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viewallaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viewallaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viewallaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Viewallaccount dialog = new Viewallaccount(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Accountlist;
    private javax.swing.JButton Authentification;
    private javax.swing.JPanel Contents;
    private javax.swing.JButton Delete;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Logo;
    // End of variables declaration//GEN-END:variables
}
